remote_theme: pmarsceill/just-the-docs
footer_content: "Copyright &copy; 2019-2020 yaBobJonez (ya_Bob_Jonez). Distributed by a <a href=\"https://github.com/yaBobJonez/yaWeather/blob/master/LICENSE.html\">DERL License.</a>"